# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NSim.ui'
#
# Created: Tue Jan 14 20:41:45 2014
#      by: PyQt5 UI code generator 5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NSim(object):
    def setupUi(self, NSim):
        NSim.setObjectName("NSim")
        NSim.resize(981, 468)
        NSim.setMinimumSize(QtCore.QSize(981, 468))
        NSim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        NSim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(NSim)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SearchGroup = QtWidgets.QGroupBox(NSim)
        self.SearchGroup.setMaximumSize(QtCore.QSize(16777215, 113))
        self.SearchGroup.setObjectName("SearchGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SearchGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnFirst = QtWidgets.QPushButton(self.SearchGroup)
        self.btnFirst.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFirst.setIcon(icon)
        self.btnFirst.setFlat(True)
        self.btnFirst.setObjectName("btnFirst")
        self.horizontalLayout_7.addWidget(self.btnFirst)
        self.btnPrev = QtWidgets.QPushButton(self.SearchGroup)
        self.btnPrev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrev.setIcon(icon1)
        self.btnPrev.setFlat(True)
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout_7.addWidget(self.btnPrev)
        self.btnNext = QtWidgets.QPushButton(self.SearchGroup)
        self.btnNext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon2)
        self.btnNext.setFlat(True)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_7.addWidget(self.btnNext)
        self.btnLast = QtWidgets.QPushButton(self.SearchGroup)
        self.btnLast.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLast.setIcon(icon3)
        self.btnLast.setFlat(True)
        self.btnLast.setObjectName("btnLast")
        self.horizontalLayout_7.addWidget(self.btnLast)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.SearchGroup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btnFind = QtWidgets.QPushButton(self.SearchGroup)
        self.btnFind.setObjectName("btnFind")
        self.gridLayout.addWidget(self.btnFind, 0, 3, 1, 1)
        self.txtSearch = QtWidgets.QLineEdit(self.SearchGroup)
        self.txtSearch.setObjectName("txtSearch")
        self.gridLayout.addWidget(self.txtSearch, 0, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.SearchGroup)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 2, 0, 1, 1)
        self.txtFEPFolder = QtWidgets.QLineEdit(self.SearchGroup)
        self.txtFEPFolder.setReadOnly(True)
        self.txtFEPFolder.setObjectName("txtFEPFolder")
        self.gridLayout.addWidget(self.txtFEPFolder, 2, 1, 1, 1)
        self.btnFEPFolder = QtWidgets.QPushButton(self.SearchGroup)
        self.btnFEPFolder.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/Folder-Open-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFEPFolder.setIcon(icon4)
        self.btnFEPFolder.setFlat(True)
        self.btnFEPFolder.setObjectName("btnFEPFolder")
        self.gridLayout.addWidget(self.btnFEPFolder, 2, 2, 1, 1)
        self.lblCurPos = QtWidgets.QLabel(self.SearchGroup)
        self.lblCurPos.setObjectName("lblCurPos")
        self.gridLayout.addWidget(self.lblCurPos, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.SearchGroup)
        self.groupBox = QtWidgets.QGroupBox(NSim)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtGender = QtWidgets.QLineEdit(self.groupBox)
        self.txtGender.setMinimumSize(QtCore.QSize(277, 0))
        self.txtGender.setReadOnly(True)
        self.txtGender.setObjectName("txtGender")
        self.gridLayout_2.addWidget(self.txtGender, 3, 3, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.txtSubscriberID = QtWidgets.QLineEdit(self.groupBox)
        self.txtSubscriberID.setMinimumSize(QtCore.QSize(277, 0))
        self.txtSubscriberID.setReadOnly(True)
        self.txtSubscriberID.setObjectName("txtSubscriberID")
        self.gridLayout_2.addWidget(self.txtSubscriberID, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 2, 1, 1)
        self.txtDateOfBirth = QtWidgets.QLineEdit(self.groupBox)
        self.txtDateOfBirth.setMinimumSize(QtCore.QSize(277, 0))
        self.txtDateOfBirth.setReadOnly(True)
        self.txtDateOfBirth.setObjectName("txtDateOfBirth")
        self.gridLayout_2.addWidget(self.txtDateOfBirth, 4, 3, 1, 2)
        self.txtRegistrationTime = QtWidgets.QLineEdit(self.groupBox)
        self.txtRegistrationTime.setMinimumSize(QtCore.QSize(277, 0))
        self.txtRegistrationTime.setReadOnly(True)
        self.txtRegistrationTime.setObjectName("txtRegistrationTime")
        self.gridLayout_2.addWidget(self.txtRegistrationTime, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtFepCode = QtWidgets.QLineEdit(self.groupBox)
        self.txtFepCode.setMinimumSize(QtCore.QSize(277, 0))
        self.txtFepCode.setReadOnly(True)
        self.txtFepCode.setObjectName("txtFepCode")
        self.gridLayout_2.addWidget(self.txtFepCode, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.txtSurname = QtWidgets.QLineEdit(self.groupBox)
        self.txtSurname.setMinimumSize(QtCore.QSize(277, 0))
        self.txtSurname.setReadOnly(True)
        self.txtSurname.setObjectName("txtSurname")
        self.gridLayout_2.addWidget(self.txtSurname, 0, 3, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 7, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtFEPTrackingID = QtWidgets.QLineEdit(self.groupBox)
        self.txtFEPTrackingID.setMinimumSize(QtCore.QSize(277, 0))
        self.txtFEPTrackingID.setReadOnly(True)
        self.txtFEPTrackingID.setObjectName("txtFEPTrackingID")
        self.gridLayout_2.addWidget(self.txtFEPTrackingID, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.txtFirstName = QtWidgets.QLineEdit(self.groupBox)
        self.txtFirstName.setMinimumSize(QtCore.QSize(277, 0))
        self.txtFirstName.setReadOnly(True)
        self.txtFirstName.setObjectName("txtFirstName")
        self.gridLayout_2.addWidget(self.txtFirstName, 1, 3, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 8, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtRegistrationType = QtWidgets.QLineEdit(self.groupBox)
        self.txtRegistrationType.setMinimumSize(QtCore.QSize(277, 0))
        self.txtRegistrationType.setReadOnly(True)
        self.txtRegistrationType.setObjectName("txtRegistrationType")
        self.gridLayout_2.addWidget(self.txtRegistrationType, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 2, 1, 1)
        self.txtMotherMaidenName = QtWidgets.QLineEdit(self.groupBox)
        self.txtMotherMaidenName.setMinimumSize(QtCore.QSize(277, 0))
        self.txtMotherMaidenName.setReadOnly(True)
        self.txtMotherMaidenName.setObjectName("txtMotherMaidenName")
        self.gridLayout_2.addWidget(self.txtMotherMaidenName, 2, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.txtFolioVersion = QtWidgets.QLineEdit(self.groupBox)
        self.txtFolioVersion.setMinimumSize(QtCore.QSize(277, 0))
        self.txtFolioVersion.setReadOnly(True)
        self.txtFolioVersion.setObjectName("txtFolioVersion")
        self.gridLayout_2.addWidget(self.txtFolioVersion, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 6, 4, 1, 1)
        self.txtMainMobileNumber = QtWidgets.QLineEdit(self.groupBox)
        self.txtMainMobileNumber.setMinimumSize(QtCore.QSize(138, 0))
        self.txtMainMobileNumber.setReadOnly(True)
        self.txtMainMobileNumber.setObjectName("txtMainMobileNumber")
        self.gridLayout_2.addWidget(self.txtMainMobileNumber, 8, 3, 1, 1)
        self.txtNationality = QtWidgets.QLineEdit(self.groupBox)
        self.txtNationality.setMinimumSize(QtCore.QSize(138, 0))
        self.txtNationality.setReadOnly(True)
        self.txtNationality.setObjectName("txtNationality")
        self.gridLayout_2.addWidget(self.txtNationality, 7, 3, 1, 1)
        self.lblPortraitData = QtWidgets.QLabel(self.groupBox)
        self.lblPortraitData.setMinimumSize(QtCore.QSize(100, 100))
        self.lblPortraitData.setMaximumSize(QtCore.QSize(100, 248))
        self.lblPortraitData.setText("")
        self.lblPortraitData.setPixmap(QtGui.QPixmap(":/images/person.png"))
        self.lblPortraitData.setScaledContents(True)
        self.lblPortraitData.setObjectName("lblPortraitData")
        self.gridLayout_2.addWidget(self.lblPortraitData, 0, 5, 5, 1)
        self.txtRegistrationState = QtWidgets.QLineEdit(self.groupBox)
        self.txtRegistrationState.setMinimumSize(QtCore.QSize(277, 0))
        self.txtRegistrationState.setReadOnly(True)
        self.txtRegistrationState.setObjectName("txtRegistrationState")
        self.gridLayout_2.addWidget(self.txtRegistrationState, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.txtResidentialAddress = QtWidgets.QLineEdit(self.groupBox)
        self.txtResidentialAddress.setMinimumSize(QtCore.QSize(277, 0))
        self.txtResidentialAddress.setReadOnly(True)
        self.txtResidentialAddress.setObjectName("txtResidentialAddress")
        self.gridLayout_2.addWidget(self.txtResidentialAddress, 5, 3, 1, 2)
        self.txtRegistrationLGA = QtWidgets.QLineEdit(self.groupBox)
        self.txtRegistrationLGA.setMinimumSize(QtCore.QSize(277, 0))
        self.txtRegistrationLGA.setReadOnly(True)
        self.txtRegistrationLGA.setObjectName("txtRegistrationLGA")
        self.gridLayout_2.addWidget(self.txtRegistrationLGA, 8, 1, 1, 1)
        self.txtResidentialAddressState = QtWidgets.QLineEdit(self.groupBox)
        self.txtResidentialAddressState.setMinimumSize(QtCore.QSize(138, 0))
        self.txtResidentialAddressState.setReadOnly(True)
        self.txtResidentialAddressState.setObjectName("txtResidentialAddressState")
        self.gridLayout_2.addWidget(self.txtResidentialAddressState, 6, 5, 1, 1)
        self.txtResidentialAddressLGA = QtWidgets.QLineEdit(self.groupBox)
        self.txtResidentialAddressLGA.setMinimumSize(QtCore.QSize(138, 0))
        self.txtResidentialAddressLGA.setReadOnly(True)
        self.txtResidentialAddressLGA.setObjectName("txtResidentialAddressLGA")
        self.gridLayout_2.addWidget(self.txtResidentialAddressLGA, 6, 3, 1, 1)
        self.txtRegistrationDate = QtWidgets.QLineEdit(self.groupBox)
        self.txtRegistrationDate.setMinimumSize(QtCore.QSize(277, 0))
        self.txtRegistrationDate.setReadOnly(True)
        self.txtRegistrationDate.setObjectName("txtRegistrationDate")
        self.gridLayout_2.addWidget(self.txtRegistrationDate, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 9, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 9, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 9, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 9, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 9, 5, 1, 1)
        self.txtStateOfOrigin = QtWidgets.QLineEdit(self.groupBox)
        self.txtStateOfOrigin.setMinimumSize(QtCore.QSize(138, 0))
        self.txtStateOfOrigin.setReadOnly(True)
        self.txtStateOfOrigin.setObjectName("txtStateOfOrigin")
        self.gridLayout_2.addWidget(self.txtStateOfOrigin, 7, 5, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.btnExit = QtWidgets.QPushButton(NSim)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_5.addWidget(self.btnExit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.label_6.setBuddy(self.txtSubscriberID)
        self.label_15.setBuddy(self.txtDateOfBirth)
        self.label_16.setBuddy(self.txtResidentialAddress)
        self.label_8.setBuddy(self.txtRegistrationTime)
        self.label_17.setBuddy(self.txtResidentialAddressLGA)
        self.label_9.setBuddy(self.txtRegistrationState)
        self.label_10.setBuddy(self.txtRegistrationLGA)
        self.label_19.setBuddy(self.txtNationality)
        self.label_2.setBuddy(self.txtFepCode)
        self.label_11.setBuddy(self.txtSurname)
        self.label_20.setBuddy(self.txtStateOfOrigin)
        self.label_3.setBuddy(self.txtFEPTrackingID)
        self.label_12.setBuddy(self.txtFirstName)
        self.label_21.setBuddy(self.txtMainMobileNumber)
        self.label_4.setBuddy(self.txtRegistrationType)
        self.label_13.setBuddy(self.txtMotherMaidenName)
        self.label_5.setBuddy(self.txtFolioVersion)
        self.label_14.setBuddy(self.txtGender)
        self.label_18.setBuddy(self.txtResidentialAddressState)
        self.label_7.setBuddy(self.txtRegistrationDate)

        self.retranslateUi(NSim)
        self.btnExit.clicked.connect(NSim.close)
        QtCore.QMetaObject.connectSlotsByName(NSim)
        NSim.setTabOrder(self.txtSearch, self.btnFind)
        NSim.setTabOrder(self.btnFind, self.btnFEPFolder)
        NSim.setTabOrder(self.btnFEPFolder, self.btnFirst)
        NSim.setTabOrder(self.btnFirst, self.btnPrev)
        NSim.setTabOrder(self.btnPrev, self.btnNext)
        NSim.setTabOrder(self.btnNext, self.btnLast)
        NSim.setTabOrder(self.btnLast, self.txtFepCode)
        NSim.setTabOrder(self.txtFepCode, self.txtFEPTrackingID)
        NSim.setTabOrder(self.txtFEPTrackingID, self.txtRegistrationType)
        NSim.setTabOrder(self.txtRegistrationType, self.txtFolioVersion)
        NSim.setTabOrder(self.txtFolioVersion, self.txtSubscriberID)
        NSim.setTabOrder(self.txtSubscriberID, self.txtSurname)
        NSim.setTabOrder(self.txtSurname, self.txtFirstName)
        NSim.setTabOrder(self.txtFirstName, self.txtMotherMaidenName)
        NSim.setTabOrder(self.txtMotherMaidenName, self.txtGender)
        NSim.setTabOrder(self.txtGender, self.txtDateOfBirth)
        NSim.setTabOrder(self.txtDateOfBirth, self.txtFEPFolder)
        NSim.setTabOrder(self.txtFEPFolder, self.btnExit)

    def retranslateUi(self, NSim):
        _translate = QtCore.QCoreApplication.translate
        NSim.setWindowTitle(_translate("NSim", "NSim Demographics Viewer"))
        self.SearchGroup.setTitle(_translate("NSim", "Search Parameter"))
        self.label.setText(_translate("NSim", "File Name:"))
        self.btnFind.setText(_translate("NSim", "Find"))
        self.label_22.setText(_translate("NSim", "FEP Folder:"))
        self.lblCurPos.setText(_translate("NSim", "#{0} of {1} items"))
        self.groupBox.setTitle(_translate("NSim", "Registration Details"))
        self.label_6.setText(_translate("NSim", "Subscriber ID:"))
        self.label_15.setText(_translate("NSim", "Date of Birth:"))
        self.label_16.setText(_translate("NSim", "Residential Address:"))
        self.label_8.setText(_translate("NSim", "Registration Time:"))
        self.label_17.setText(_translate("NSim", "Residential Address LGA:"))
        self.label_9.setText(_translate("NSim", "Registration State:"))
        self.label_10.setText(_translate("NSim", "Registration LGA:"))
        self.label_19.setText(_translate("NSim", "Nationality:"))
        self.label_2.setText(_translate("NSim", "FEP Code:"))
        self.label_11.setText(_translate("NSim", "Surname:"))
        self.label_20.setText(_translate("NSim", "State of Origin:"))
        self.label_3.setText(_translate("NSim", "FEP Tracking ID:"))
        self.label_12.setText(_translate("NSim", "First Name:"))
        self.label_21.setText(_translate("NSim", "Main Mobile Number:"))
        self.label_4.setText(_translate("NSim", "Registration Type:"))
        self.label_13.setText(_translate("NSim", "Mother\'s Maiden Name:"))
        self.label_5.setText(_translate("NSim", "Folio Version:"))
        self.label_14.setText(_translate("NSim", "Gender:"))
        self.label_18.setText(_translate("NSim", "Residential Address State:"))
        self.label_7.setText(_translate("NSim", "Registration Date:"))
        self.btnExit.setText(_translate("NSim", "E&xit"))

import resources_rc
