# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchDlg.ui'
#
# Created: Wed Mar 19 15:28:16 2014
#      by: PyQt5 UI code generator 5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchDlg(object):
    def setupUi(self, SearchDlg):
        SearchDlg.setObjectName("SearchDlg")
        SearchDlg.resize(602, 334)
        SearchDlg.setMinimumSize(QtCore.QSize(602, 334))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SearchDlg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(SearchDlg)
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtMobileNo = QtWidgets.QLineEdit(self.groupBox)
        self.txtMobileNo.setMaxLength(11)
        self.txtMobileNo.setObjectName("txtMobileNo")
        self.gridLayout.addWidget(self.txtMobileNo, 0, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.btnFolder = QtWidgets.QPushButton(self.groupBox)
        self.btnFolder.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Folder-Open-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFolder.setIcon(icon)
        self.btnFolder.setFlat(True)
        self.btnFolder.setObjectName("btnFolder")
        self.gridLayout.addWidget(self.btnFolder, 1, 1, 1, 1)
        self.lblFolder = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolder.sizePolicy().hasHeightForWidth())
        self.lblFolder.setSizePolicy(sizePolicy)
        self.lblFolder.setText("")
        self.lblFolder.setObjectName("lblFolder")
        self.gridLayout.addWidget(self.lblFolder, 1, 2, 1, 2)
        self.btnSearch = QtWidgets.QPushButton(self.groupBox)
        self.btnSearch.setMaximumSize(QtCore.QSize(77, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout.addWidget(self.btnSearch, 2, 1, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SearchDlg)
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(SearchDlg)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(260)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.label_2.setBuddy(self.txtMobileNo)
        self.label_3.setBuddy(self.btnFolder)

        self.retranslateUi(SearchDlg)
        QtCore.QMetaObject.connectSlotsByName(SearchDlg)

    def retranslateUi(self, SearchDlg):
        _translate = QtCore.QCoreApplication.translate
        SearchDlg.setWindowTitle(_translate("SearchDlg", "NSIM Demographics Viewer"))
        self.groupBox.setTitle(_translate("SearchDlg", "Search Parameters"))
        self.label_2.setText(_translate("SearchDlg", "Mobile No.:"))
        self.label_3.setText(_translate("SearchDlg", "FEP/MNO Folder:"))
        self.btnSearch.setText(_translate("SearchDlg", "Search"))
        self.label.setText(_translate("SearchDlg", "Matched Items"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchDlg", "Packet"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchDlg", "XML Filename"))

import resources_rc
